### ISSUE TITLE
mixed tabs and spaces

### ISSUE THREAD

**Issue by Daniel-Hug** [emmetio/codemirror#14]
## Case 1

In the [expand abbreviation demo](http://docs.emmet.io/actions/expand-abbreviation/), when you "try it yourself" and expand an abbreviation like `ul>li`, the `<li>` will be indented with a tab, even though the code in the editor is indented using spaces.
## Case 2

[JS Bin](http://jsbin.com/) uses Code Mirror and the emmet plugin. This same bug exists in reverse there: https://github.com/jsbin/jsbin/issues/2153 The child gets indented with 2 spaces though the editor is configured to indent with tabs and all preexisting html is also tab-indented.

**Comment by sergeche** [comment]
Was fixed long ago, works fine in current repo (docs web-site has outdated plugin)
