### ISSUE TITLE
Support for CodeMirror 5.x

### ISSUE THREAD

**Issue by ingro** [emmetio/codemirror#15]
Hello, reading from the docs it seems that this plugin should work on CodeMirror 4.x+, but I can't get it to work with CodeMirror 5.5. Am I doing something wrong or it's just that the plugin doesn't support CodeMirror 5.x?

Thank you.

**Comment by sergeche** [comment]
CodeMirror 5 is supported: https://github.com/emmetio/codemirror/blob/master/package.json#L32

**Comment by ingro** [comment]
Thanks for the reply, so it should be some issue on my side, I guess caused by Webpack.
