### ISSUE TITLE
toggle emmet plugin on/off

### ISSUE THREAD

**Issue by markhillard** [emmetio/codemirror#18]
I've successfully initialized the Emmet plugin for CodeMirror using `emmetCodeMirror()`, but is there a way to destroy it or stop it from running? What I'm trying to do is create a toggle that switches the plugin on and off. Starting it is easy, but I'm not sure if there's a way to stop it and then start it back up on a click event.

I'm running CodeMirror 5.13.2 if that makes any difference.

**Comment by sergeche** [comment]
There’s a [`dispose` method](https://github.com/emmetio/codemirror/blob/master/plugin.js#L56) to turn off Emmet keymaps

**Comment by markhillard** [comment]
Thanks @sergeche! This is exactly what I need.

**Comment by sergeche** [comment]
Note that in upcoming update there’s slightly changed API: this method should be imported directly: https://github.com/emmetio/codemirror/blob/webpack/plugin.js#L66

**Comment by markhillard** [comment]
@sergeche, how would I use the dispose method? I know to initialize it you run this: `emmetCodeMirror(editorHTML);`

I tried chaining `.dispose();` after it, but it didn't work.

**Comment by sergeche** [comment]
Old (current) version:

``` js
import emmetPlugin from 'emmet-codemirror';

emmetPlugin(cmEditor); // enable
emmetPlugin.dispose(cmEditor); // disable
```

New version (currently in `webpack` branch):

``` js
import {default as emmetPlugin, dispose} from 'emmet-codemirror';

emmetPlugin(cmEditor); // enable
dispose(cmEditor); // disable
```

**Comment by markhillard** [comment]
Thank you @sergeche. Much appreciated.

**Comment by markhillard** [comment]
FYI, this is what I'm working on: http://markhillard.github.io/Editor/
