### ISSUE TITLE
Calle is deprecated

### ISSUE THREAD

**Issue by jotakar** [emmetio/codemirror#26]
I don't know if this project is abandoned, but I notice that this plugin use olde javascript style like arguments.callee
Is anybody updating this? If it doesn't please some bod could mark it as abandoned or closed or so.. 
Thanks

**Comment by sergeche** [comment]
Most recent plugin version is here: https://github.com/emmetio/codemirror-plugin

**Comment by jotakar** [comment]
Thanks!!
