### ISSUE TITLE
codemirror 4 support

### ISSUE THREAD

**Issue by paulirish** [emmetio/codemirror#7]
In Chrome DevTools we just updated to CM4.

We'd be very interested in using this plugin directly inside DevTools if it's compatible. 

ref: http://code.google.com/p/chromium/issues/detail?id=360242
cc @aslushnikov

**Comment by Haroenv** [comment]
How come this isn't closed, the readme says compatible with 4.x, and another said 5.x even

**Comment by sergeche** [comment]
Yep, also works with 5.x
